### PR TITLE
My first work

### PR DESCRIPTION
**Pull request by RichardJanzen**
Here I already worked on a possible start for a page about Home-Office and changed the overall theme.
The code may seem a bit ruff at times, so feel free to leave suggestions or questions.

For example, line 40 of the "HomeOffice.rmd" creates a vector for the positions of the percentages inside the piechart. The method from above, lines 35-38, copied from the internet, didn't yield the best positions and thus had to be changed manually.

I did work with the original Dataset, but didn't upload it in my repository, for security reasons.

Cheers!

### CODE REVIEW

**Review by cortrudolph — APPROVED** [review]

**Comment by cortrudolph** [comment]
Thanks, Richard! 

For this to "work" we will need to have the data linked here somehow. I suggest that, for now, we work with .CSV files that include just the variables we want (e.g., for home office). I would recommend that you subset those variables out, export a .CSV (e.g., `write.csv()`) and then we can put this in the data folder.

**Comment by cortrudolph** [comment]
Actually, never mind -- it looks like this worked! 👍 https://cortrudolph.github.io/COVID_19_Dashboard/analysis.html

**Comment by cortrudolph** [comment]
Actually, never mind -- it looks like this worked! 👍 https://cortrudolph.github.io/COVID_19_Dashboard/index.html

**Comment by RichardJanzen** [comment]
I suppose it worked, because I built the website locally, where I do have the data available, and afterwards just uploaded the .html files with the graphs etc. already incorporated. But You are right, down the workflow, especially if we decide to put some interactive elements into some of the sites, we will have to find a better way to do this.

**Pull request merged**
